### ISSUE TITLE
Implement Calculation of Total Travel Distance for a Given Drone

### ISSUE THREAD

**Issue by zakaBouj** [Code-Hauptwache/DroneDeck#50]
### **Description**
The `DashboardDroneCardDto` currently includes a placeholder method `getTravelDistance()` that returns `null`. This method is intended to calculate the total travel distance of a given drone based on its flight data or GPS coordinates. However, this functionality has not yet been implemented. This issue aims to add the logic for calculating the total travel distance of a drone.

---

### **Requirements**
1. **Input Data**:
   - The drone's GPS coordinates (`longitude` and `latitude`).
   - Historical GPS data or flight logs, if available.

2. **Functionality**:
   - Calculate the total distance traveled by the drone using the Haversine formula or other appropriate methods to compute the distance between two geographical points.
   - The method should iterate over the GPS points (or flight data) to sum up the distances between consecutive points.

3. **Minimizing API Requests**:
   - Minimize the number of API requests to the drone's backend or telemetry API while ensuring precise results for the travel distance.
   - Use an efficient polling or data-caching mechanism to avoid frequent redundant API calls while maintaining accurate calculations.

4. **Output**:
   - The method `getTravelDistance()` should return a `double` value representing the total travel distance in kilometers or meters.

5. **Edge Cases**:
   - Handle cases where no GPS data is available (e.g., return `0`).
   - Ensure the method works correctly for drones that cross the international date line.

---

### **Proposed Changes**
1. Modify the `DashboardDroneCardDto` class (introduced in #24)  to include the logic for calculating the travel distance:
   - Add a list of GPS points (`List<Coordinate>` or similar structure) to hold the historical flight data.
   - Implement the `getTravelDistance()` method to calculate and return the total distance.

2. Optionally, create a service class (`DroneTravelDistanceService`) to handle the distance calculation. This will:
   - Encapsulate the calculation logic.
   - Keep `DashboardDroneCardDto` lightweight.
   - Integrate caching or rate-limiting strategies to reduce API usage.

3. Write unit tests to ensure the correctness of the calculation.

---

### **Tasks**
- [ ] Implement the `getTravelDistance()` method in `DashboardDroneCardDto` or the service class.
- [ ] Add caching or batching mechanisms to minimize API calls while ensuring data accuracy.
- [ ] Add edge-case handling for invalid or incomplete data.
- [ ] Write unit tests to validate the calculation logic.
- [ ] Update relevant documentation.

---

### **Acceptance Criteria**
- The `getTravelDistance()` method accurately calculates the total travel distance using provided GPS data.
- Unit tests verify correctness for:
  - Straight-line paths.
  - Multi-point paths.
  - Edge cases (e.g., no GPS data, crossing the international date line).
- API requests to the drone backend are minimized while maintaining accurate results.
- The calculation works efficiently with large datasets.

---

### **Resources**
- **Haversine Formula**: [Link to Explanation](https://en.wikipedia.org/wiki/Haversine_formula)
- **Java Implementation Example**:
  ```java
  public static double haversine(double lat1, double lon1, double lat2, double lon2) {
      final int R = 6371; // Radius of the Earth in kilometers
      double dLat = Math.toRadians(lat2 - lat1);
      double dLon = Math.toRadians(lon2 - lon1);
      double a = Math.sin(dLat / 2) * Math.sin(dLat / 2)
              + Math.cos(Math.toRadians(lat1)) * Math.cos(Math.toRadians(lat2))
              * Math.sin(dLon / 2) * Math.sin(dLon / 2);
      double c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
      return R * c; // Distance in kilometers
  }
  ```

**Comment by RoundTable02** [comment]
Does DashboardDroneCardDto needs List<Coordinate>? If not I would like to change the field List<Coordinate> into just double(total travel distance)

**Comment by zakaBouj** [comment]
> Does DashboardDroneCardDto need the List field? If not I would like to change the field List into just double(total travel distance)

@RoundTable02 are you referring to the return type of the `getTravelDistance` getter? I'm not entirely sure what you're referring to - could you clarify?

**Comment by RoundTable02** [comment]
Yes, in first task it said "Add a List<Coordinate> field to DashboardDroneCardDto to store GPS data" but I don't think List<Coordinate> field is necessary in DTO. Instead, it needs field for total travel distance. Can I change like that?

**Comment by zakaBouj** [comment]
> Yes, in first task it said "Add a List field to DashboardDroneCardDto to store GPS data" but I don't think List field is necessary in DTO. Instead, it needs field for total travel distance. Can I change like that?

@RoundTable02 oh yes sure, just returning the total travel distance should be more than enough 👍
